# Generated by Django 5.0 on 2024-01-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
