# Generated by Django 5.0 on 2024-01-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField()),
                ('enrollment_type', models.CharField(blank=True, choices=[('returning', 'Returning'), ('transferree', 'Transferree')], max_length=50)),
            ],
        ),
    ]
