# Generated by Django 5.0 on 2024-01-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(blank=True, choices=[('returning', 'Returning'), ('transferree', 'Transferree')], max_length=50),
        ),
    ]
