# Generated by Django 5.0 on 2024-01-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_sch_id',
            field=models.CharField(default='123abc', max_length=50),
            preserve_default=False,
        ),
    ]
